### ISSUE TITLE
DRY in css rules

### ISSUE THREAD

**Issue by joostf** [boudewijnbout/the-web-is-for-everyone-chippr.dev#18]
For example this rule is repeated in all stylesheets. Use one global sheet for common rules?!

```css
* {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
} 
```
